
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_install:
    - .aws/credentials
    - pip install --user awscli
node_js:
  - '9'
script:
  - cd instacar-task-api && npm i
  - npm run deploy && cd..
  - cd instacar-task-app && npm i
  - npm run build:serverless:deploy && cd..
after_success:
  - npm run travis-deploy-once
branches:
  except:
    - /^v\d+\.\d+\.\d+$/