
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_install:
    - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
    - 'unzip awscli-bundle.zip'
    - './awscli-bundle/install -b ~/bin/aws'
    - 'export PATH=~/bin:$PATH'
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set default.region ${AWS_DEFAULT_REGION}
node_js:
  - '9'
script:
  - cd instacar-task-api && npm i
  - npm run deploy && cd..
  - cd instacar-task-app && npm i
  - npm run build:serverless:deploy && cd..
after_success:
  - npm run travis-deploy-once
branches:
  except:
    - /^v\d+\.\d+\.\d+$/