
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_install:
    - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
    - 'unzip awscli-bundle.zip'
    - './awscli-bundle/install -b ~/bin/aws'
    - 'export PATH=~/bin:$PATH'
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set default.region ${AWS_DEFAULT_REGION}
node_js:
  - '10.15.3'
  - '9'

stages:
  - deploy_api
  - deploy_app

jobs: 
  include:
    - stage: deploy_api
      script:
        - cd instacar-task-api
        - echo 'in app'
        - npm install
        - echo 'in app'
        - npm run deploy
      after_success:
        - echo 'done'
    - stage: deploy_app
      script:
        - cd instacar-task-app
        - echo 'in app'
        - npm install
        - echo 'in app'
        - npm run build:serverless:deploy
      after_success:
        - echo 'done'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/